"use client";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import AppProvider from "@/components/providers/app-provider";
import { useEffect } from "react";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.style.fontFamily}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
